FROM node:20-alpine AS build

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./

RUN corepack enable
RUN corepack prepare pnpm@latest --activate
RUN pnpm install

COPY ./src ./src
COPY ./tsconfig.json .
COPY ./tsconfig.app.json .
COPY ./angular.json .
COPY .postcssrc.json .
 
RUN pnpm build --configuration=development

FROM nginxinc/nginx-unprivileged:alpine
COPY --from=build /usr/src/app/dist/dtf-hat/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]


