FROM node:20-alpine AS build
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install

COPY ./src ./src
COPY ./tsconfig.json .
COPY ./tsconfig.app.json .
COPY ./angular.json .
COPY .postcssrc.json .

RUN yarn build --configuration=production

FROM nginxinc/nginx-unprivileged:alpine
COPY --from=build /usr/src/app/dist/shipping/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]


