export enum ItemTransitionStatus {
  Incoming = 2,
  DropPending = 3,
  Shortage = 4,
  OverstockMoveNeeded = 5,
  WaitingForShortage = 6,
  TicketScanPending = 7,
  PickPending = 8,
  Picked = 9,
  NoStock = 10,
  PrintSorted = 11,
  AtPrinter = 12,
  ArtError = 13,
  InternalArtError = 54,
  Washing = 14,
  PartnerUpdatePending = 15,
  ArtErrorFixed = 16,
  WashingComplete = 17,
  PrintPending = 18,
  QaSuccess = 19,
  QaFailure = 20,
  ApprovalNeeded = 21,
  Labeling = 22,
  Folding = 23,
  InMerge = 24,
  ReadyToShip = 25,
  ReadyToSort = 26,
  Shipped = 27,
  ShippedProblems = 28,
  Rejected = 29,
  CancelledWithCharge = 30,
  CancelledWithoutCharge = 31,
  Labeled = 32,
  Sorted = 33,
  FontError = 34,
  ImageTesting = 35,
  ReadyToPrint = 36,
  RndPending = 37,
  VipOrderPending = 38,
  OutOfStock = 39,
  WaitingForOutOfStock = 40,
  TscMergePending = 41,
  NoStockPickPending = 42,
  TfsMergeComplete = 43,
  Merged = 45,
  NeckLabelPending = 44,
  PrintTooSmall = 46,
  PrintTooLarge = 47,
  PrintYOffsetInvalid = 48,
  PrintLocationInvalid = 49,
  PrintImageInvalid = 50,
  PrintLocationMissing = 53,
  AlertAdmin = 55,
  PriorityQueue = 70,
  IncomingReprints = 56,
  PrintWhiteOnWhite = 57,
  ReprintsPending = 58,
  ReprintsReview = 59,
  Locked = 60,
  WaitingForUnlock = 65,
  WashingFailed = 61,
  StainedSendToWash = 62,
  WashStainComplete = 63,
  WashStainFailed = 64,
  IncomingExpedited = 66,
  IncomingBlended = 67,
  IncomingLocked = 68,
  IncomingBlocked = 69,
  IncomingUnassigned = 71,
  IncomingXQC = 74,
  IncomingExpress = 75,
  DesignRejected = 76,
  WaitingForDesignRejected = 77,
  Unpublished = 78,
  NLTooSmall = 80,
  NLTooLarge = 81,
  NLImageInvalid = 82,
  InternalNLArtError = 83,
  NLArtErrorFixed = 84,
  DtfLabelMissing = 85,
  DtfLabelWrong = 86,
  DtfLabelDamaged = 87,
  DtfLabelRejected = 88,
  DtfPickUpPending = 89,
  DtfCartOpen = 90,
  DtfCartClosed = 91,
  DtfPrinted = 92,
  DtfMerged = 93,
  DtfLabelled = 94,
  ReadyToTrim = 96,
  MugPrinted = 98,
  MugPrintRejected = 99,
  PrintImageDpiInvalid = 101,
  MugPrintPending = 102,
  StickerPrintPending = 103,
  JitOnHold = 107,
  JitReOrderPending = 108,
  JitPoSubmitted = 109,
  JitMissing = 110,
  JitReceived = 111,
  JitPreMerge = 112,
  JitMerged = 113,
  JitReadyToPick = 114,
  WaitingForJitMerge = 115,
  JitPoInTransit = 116,
  JitRevisionReceived = 117,
  JitMovementCreated = 118,
  JitMovementInTransit = 119,
  JitDamaged = 120,
  PrintBlackOnBlack = 106,
  PrintImageMissing = 121,
  DesignTransparency = 122,
  WrongArt = 123,
  GarmentColorInvalid = 124,
}

export class ItemTransitionStatusMap {
  static readonly names = new Map<ItemTransitionStatus | null | undefined, string>([
    [ItemTransitionStatus.Incoming, 'Incoming'],
    [ItemTransitionStatus.DropPending, 'Drop Pending'],
    [ItemTransitionStatus.Shortage, 'Shortage'],
    [ItemTransitionStatus.OverstockMoveNeeded, 'Overstock Move Needed'],
    [ItemTransitionStatus.WaitingForShortage, 'Waiting For Shortage/OSMN'],
    [ItemTransitionStatus.TicketScanPending, 'Ticket Scan Pending'],
    [ItemTransitionStatus.PickPending, 'Pick Pending'],
    [ItemTransitionStatus.NoStock, 'Pick Hold'],
    [ItemTransitionStatus.PrintSorted, 'Print Sorted'],
    [ItemTransitionStatus.AtPrinter, 'At Printer'],
    [ItemTransitionStatus.InternalArtError, 'Art Error - Internal'],
    [ItemTransitionStatus.Washing, 'Washing'],
    [ItemTransitionStatus.PartnerUpdatePending, 'Partner Update Pending'],
    [ItemTransitionStatus.ArtErrorFixed, 'Art Error Fixed'],
    [ItemTransitionStatus.WashingComplete, 'Washing Complete'],
    [ItemTransitionStatus.PrintPending, 'Print Pending'],
    [ItemTransitionStatus.QaSuccess, 'QA Success'],
    [ItemTransitionStatus.QaFailure, 'QA Failure'],
    [ItemTransitionStatus.ApprovalNeeded, 'Approval Needed'],
    [ItemTransitionStatus.Labeling, 'Labeling'],
    [ItemTransitionStatus.Folding, 'Folding'],
    [ItemTransitionStatus.InMerge, 'In Merge'],
    [ItemTransitionStatus.ReadyToShip, 'Ready To Ship'],
    [ItemTransitionStatus.ReadyToSort, 'Ready To Sort'],
    [ItemTransitionStatus.Shipped, 'Shipped'],
    [ItemTransitionStatus.ShippedProblems, 'Shipped Problems'],
    [ItemTransitionStatus.Rejected, 'Rejected'],
    [ItemTransitionStatus.CancelledWithCharge, 'Cancel (w/ Charge)'],
    [ItemTransitionStatus.CancelledWithoutCharge, 'Cancel (w/o Charge)'],
    [ItemTransitionStatus.Labeled, 'Labeled'],
    [ItemTransitionStatus.Sorted, 'Sorted'],
    [ItemTransitionStatus.FontError, 'Font Error'],
    [ItemTransitionStatus.ImageTesting, 'Image Testing'],
    [ItemTransitionStatus.ReadyToPrint, 'Ready To Print'],
    [ItemTransitionStatus.RndPending, 'Rnd Pending'],
    [ItemTransitionStatus.VipOrderPending, 'Vip Order Pending'],
    [ItemTransitionStatus.OutOfStock, 'Out of Stock'],
    [ItemTransitionStatus.WaitingForOutOfStock, 'Waiting for Out of Stock'],
    [ItemTransitionStatus.TscMergePending, 'TSC Merge Pending'],
    [ItemTransitionStatus.NoStockPickPending, 'No Stock Pick Pending'],
    [ItemTransitionStatus.TfsMergeComplete, 'Blended Merge Complete'],
    [ItemTransitionStatus.Merged, 'Merged'],
    [ItemTransitionStatus.NeckLabelPending, 'Neck Label Pending'],
    [ItemTransitionStatus.PrintTooSmall, 'Art Error - Too Small'],
    [ItemTransitionStatus.PrintTooLarge, 'Art Error - Too Large'],
    [ItemTransitionStatus.PrintYOffsetInvalid, 'Art Error - Y-Offset Invalid'],
    [ItemTransitionStatus.PrintLocationInvalid, 'Art Error - Location Invalid'],
    [ItemTransitionStatus.PrintImageInvalid, 'Art Error - Image Invalid'],
    [ItemTransitionStatus.PrintLocationMissing, 'Art Error - Location Missing'],
    [ItemTransitionStatus.AlertAdmin, 'Alert Admin'],
    [ItemTransitionStatus.PriorityQueue, 'Priority Queue'],
    [ItemTransitionStatus.IncomingReprints, 'Incoming - Reprints'],
    [ItemTransitionStatus.PrintWhiteOnWhite, 'Art Error - White on White'],
    [ItemTransitionStatus.PrintBlackOnBlack, 'Art Error - Black on Black'],
    [ItemTransitionStatus.PrintImageMissing, 'Art Error - Print Image Missing'],
    [ItemTransitionStatus.DesignTransparency, 'Art Error - Design Transparency'],
    [ItemTransitionStatus.WrongArt, 'Art Error - Wrong Art'],
    [ItemTransitionStatus.GarmentColorInvalid, 'Art Error - Garment Color Invalid'],
    [ItemTransitionStatus.ReprintsPending, 'Reprints – Pending'],
    [ItemTransitionStatus.ReprintsReview, 'Reprints – Review'],
    [ItemTransitionStatus.Locked, 'Locked'],
    [ItemTransitionStatus.WaitingForUnlock, 'Waiting for Unlock'],
    [ItemTransitionStatus.WashingFailed, 'Washing Failed'],
    [ItemTransitionStatus.StainedSendToWash, 'Stained – Send to Wash'],
    [ItemTransitionStatus.WashStainComplete, 'Wash Stain Complete'],
    [ItemTransitionStatus.WashStainFailed, 'Wash Stain Failed'],
    [ItemTransitionStatus.IncomingBlended, 'Incoming - Blended'],
    [ItemTransitionStatus.IncomingLocked, 'Incoming - Locked'],
    [ItemTransitionStatus.IncomingBlocked, 'Incoming - Blocked'],
    [ItemTransitionStatus.IncomingExpedited, 'Incoming - Expedited'],
    [ItemTransitionStatus.IncomingUnassigned, 'Incoming - Unassigned'],
    [ItemTransitionStatus.IncomingXQC, 'Incoming - XQC'],
    [ItemTransitionStatus.IncomingExpress, 'Incoming - Express'],
    [ItemTransitionStatus.DesignRejected, 'Design Rejected'],
    [ItemTransitionStatus.WaitingForDesignRejected, 'Waiting for Design Rejected'],
    [ItemTransitionStatus.Unpublished, 'Unpublished'],
    [ItemTransitionStatus.NLTooSmall, 'NL Too Small'],
    [ItemTransitionStatus.NLTooLarge, 'NL Too Large'],
    [ItemTransitionStatus.NLImageInvalid, 'NL Image Invalid'],
    [ItemTransitionStatus.InternalNLArtError, 'Internal NL Art Error'],
    [ItemTransitionStatus.NLArtErrorFixed, 'NL Art Error Fixed'],
    [ItemTransitionStatus.DtfLabelMissing, 'DTF Label Missing'],
    [ItemTransitionStatus.DtfLabelWrong, 'DTF Label Wrong'],
    [ItemTransitionStatus.DtfLabelDamaged, 'DTF Label Damaged'],
    [ItemTransitionStatus.DtfLabelRejected, 'DTF Label Rejected'],
    [ItemTransitionStatus.DtfPickUpPending, 'DTF PickUp Pending'],
    [ItemTransitionStatus.DtfCartOpen, 'DTF Cart Open'],
    [ItemTransitionStatus.DtfCartClosed, 'DTF Cart Closed'],
    [ItemTransitionStatus.DtfMerged, 'DTF Merged'],
    [ItemTransitionStatus.DtfLabelled, 'DTF Labelled'],
    [ItemTransitionStatus.MugPrinted, 'Mug Printed'],
    [ItemTransitionStatus.MugPrintRejected, 'Mug Print Rejected'],
    [ItemTransitionStatus.PrintImageDpiInvalid, 'Art Error - Image DPI Invalid'],
    [ItemTransitionStatus.MugPrintPending, 'Mug Print Pending'],
    [ItemTransitionStatus.StickerPrintPending, 'Sticker Print Pending'],
    [ItemTransitionStatus.ReadyToTrim, 'Ready to Trim'],
    [ItemTransitionStatus.JitOnHold, 'Jit - On Hold'],
    [ItemTransitionStatus.JitReOrderPending, 'Jit - Re Order Pending'],
    [ItemTransitionStatus.JitPoSubmitted, 'Jit PO Submitted'],
    [ItemTransitionStatus.JitMissing, 'Jit Missing'],
    [ItemTransitionStatus.JitReceived, 'Jit Received'],
    [ItemTransitionStatus.JitPreMerge, 'Jit - Pre Merge'],
    [ItemTransitionStatus.JitMerged, 'Jit - Merged'],
    [ItemTransitionStatus.JitReadyToPick, 'Jit Ready To Pick'],
    [ItemTransitionStatus.WaitingForJitMerge, 'Waiting for JIT Merge'],
    [ItemTransitionStatus.JitPoInTransit, 'JIT - PO In Transit'],
    [ItemTransitionStatus.JitRevisionReceived, 'JIT - Revision Received'],
    [ItemTransitionStatus.JitMovementCreated, 'JIT - Movement Created'],
    [ItemTransitionStatus.JitMovementInTransit, 'JIT - Movement In Transit'],
    [ItemTransitionStatus.JitDamaged, 'Jit Damaged'],
  ]);
}
