export enum PrinterType {
  StandardPrinter = 0,
  Expedited = 1,
  Regular = 2,
  Priority = 3,
  ShipStation = 4,
  Other = 5,
  Receiving = 6,
  _2ddRegular = 7,
  _2ddPriority = 8,
  BOL = 9,
  HangTag = 10,
  Sorting = 11,
  CustomInsert = 12,
  JitRegular = 15,
  JitPriority = 16,
  DTFHatRegular = 17,
  EmbRegular = 18,
  PreQR = 19,
  SockRegular = 20,
}
